### ISSUE TITLE
Login page bugs

### ISSUE THREAD

**Issue by afc163** [ant-design/test2#11]
- [x] 页面有横向滚动条。
- [x] 接口报错的（500/404）时候，没有任何显示。
- [x] 使用 admin/888888 时无法登录（在 gh-pages 上时），是否不用走后台接口，直接登录成功？

**Comment by afc163** [comment]
第三点，@nikogu 也可以关注下，roadhog-api-doc 静态化还不支持 post 的数据。

**Comment by nikogu** [comment]
应该是支持的，我改改

**Comment by afc163** [comment]
https://travis-ci.org/ant-design/test2/jobs/274198763 导致这个用例过不了。

**Comment by afc163** [comment]
@nikogu 有进展么

**Comment by nikogu** [comment]
下午立马改！

**Comment by nikogu** [comment]
https://github.com/ant-design/test2/commit/6470e034d19306b964a961a1c1f157ec38648173

**Comment by afc163** [comment]
其他两个问题你也一起改了？...应该是 @ddcat1115 的锅。

**Comment by nikogu** [comment]
顺手一并修改 ＝。- ....
