### ISSUE TITLE
分析页问题

### ISSUE THREAD

**Issue by afc163** [ant-design/test2#12]
<img width="264" alt="image" src="https://user-images.githubusercontent.com/507615/30413637-d2c6b24e-9951-11e7-932b-d6be2369d8c9.png">

**Comment by nikogu** [comment]
😢 我加个例子。。。

**Comment by afc163** [comment]
是边距问题。

**Comment by nikogu** [comment]
close 还写错了。。汗。。

**Comment by afc163** [comment]
写错两次了。
