### ISSUE TITLE
响应式问题收集

### ISSUE THREAD

**Issue by afc163** [ant-design/test2#14]
重现方式，缩小浏览器窗口到最小。

- [x] 分步表单页，Steps 应换行，提交按钮应对齐。@afc163
- [x] 结果页，文字被压缩成一列，图标不对齐。@ddcat1115
- [x] 各种列表页：内容区域应纵向换行展示。@nikogu

**Comment by nikogu** [comment]
@ddcat1115 还有 `PageHeader` 可能要处理下

**Comment by nikogu** [comment]
https://github.com/ant-design/test2/commit/c4d9e025828631b8257a16132a15a6111ccb2727

List 组件已经处理了小屏的换行问题，但是我们例子中的场景比较自定义一些，需要强制换行才好看，所以额外添加了样式。

**Comment by afc163** [comment]
- [ ] 高级详情页页头。@ddcat1115

<img width="574" alt="image" src="https://user-images.githubusercontent.com/507615/30844092-c3e5731a-a2bf-11e7-830c-22627411653e.png">

**Comment by afc163** [comment]
改完的自行勾上。

**Comment by ddcat1115** [comment]
pageHeader e6d23aed9be7c987358a87827d122d8b482af520
