### ISSUE TITLE
视觉样式更新

### ISSUE THREAD

**Issue by afc163** [ant-design/test2#16]
视觉稿已经根据 antd 3.0 整体更新，有一些细节改动，云雀地址：`{larkurl}/ui-assets/sketch`，及时跟进。

- [x] 布局 @afc163 
- [x] Dashboard @nikogu  https://github.com/ant-design/test2/commit/402532cd98cc3634ddb52ccbd0dff6fccfb11f78
    - [x] 分析页
    - [x] 监控页
    - [x] 工作台
- [x] 列表页 @nikogu  https://github.com/ant-design/test2/commit/05ca4cf82b08f05d548267d627950e5348c32fb5
    - [x] 标准表格（表格查询）
    - [x] 标准列表
    - [x] 卡片列表
    - [x] 卡片列表（封面）
    - [x] 待筛选的卡片列表
    - [x] 搜索列表
- [x] 表单页 @afc163 
    - [x] 基础表单
    - [x] 分步表单
    - [x] 高级表单
- [x] 详情页 @ddcat1115 
  - [x] 基础详情
  - [x] 高级详情 `Steps 组件点状样式需要升级，支持 title 和 description 左对齐，同时步骤点周围有空白`
- [x] 账户 @ddcat1115 
    - [x] 登陆
    - [x] 注册
    - [x] 注册结果
- [x] 结果 @ddcat1115 
    - [x] 成功
    - [x] 失败
- [x] 错误 @ddcat1115 
    - [x] 403 
    - [x] 404
    - [x] 500

**Comment by afc163** [comment]
预计下周一完成改造。

**Comment by momozzzxy** [comment]
。。。。视觉稿全部迭代完成是这周五。。你要逼死他们么

**Comment by afc163** [comment]
预计下周五完成改造。
