### ISSUE TITLE
Upgrade to dva@2 and dva-react

### ISSUE THREAD

**Issue by afc163** [ant-design/test2#5]
https://github.com/dvajs/dva/pull/1119

**Comment by afc163** [comment]
看看有没有可能升到 react-router@4

**Comment by ddcat1115** [comment]
dva-react（改成 dva-react-router-3 了） 才能兼容老版本，dva@2 写法上有好些 break changes，感觉脚手架得有两个版本了？

**Comment by afc163** [comment]
留一个版本。

**Comment by ddcat1115** [comment]
那就升 dva@2了，基于 react-router@4

**Comment by afc163** [comment]
menu 生成和 breadcrumb 可能不好搞，react-router 4 是去中心化的。

**Comment by ddcat1115** [comment]
👌 先学习下~
